name: Build Desktop App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps
          npm install electron@30.0.0 --save-dev --legacy-peer-deps

      - name: Build and Package App
        run: npm run build && npx electron-builder --win nsis portable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Executables
        uses: actions/upload-artifact@v4
        with:
          name: LightVideoEditor-Windows
          path: dist/*.exe
